-- Seed gem_catalog with 9 planet-significator gems × 3 tiers = 27 SKUs
-- Run AFTER 003_gem_marketplace.sql
-- Prices in paise (₹1 = 100 paise)

INSERT INTO gem_catalog (sku, name, sanskrit_name, planet, rashi, color, carat_min, carat_max, carat_default, tier, cert_authority, retail_price_paise, astrologer_cost_paise, base_commission_pct, image_url, description, benefits, contraindications)
VALUES
-- ── SUN: Ruby ─────────────────────────────────────────────
('RU-PREM',     'Ruby (Manik) Premium',       'माणिक्य',  'Sun',     ARRAY['Leo'],                  'Red',         3.0, 8.0, 5.0, 'premium',  'GIA + GRS',     5000000, 3500000, 22, NULL, 'Pigeon-blood Burmese ruby. Lab-certified vivid red.',                  'Confidence, leadership, vitality. Recommended for weak/afflicted Sun.',         'Avoid if Sun is malefic in 6/8/12.'),
('RU-STAN',     'Ruby (Manik) Standard',      'माणिक्य',  'Sun',     ARRAY['Leo'],                  'Red',         2.0, 5.0, 3.0, 'standard', 'IGI + GJEPC',   1500000, 1000000, 20, NULL, 'Ceylon ruby, eye-clean.',                                              'Confidence, paternal harmony.',                                                  'Same as premium.'),
('RU-BUDG',     'Ruby (Manik) Budget',        'माणिक्य',  'Sun',     ARRAY['Leo'],                  'Red',         1.5, 3.0, 2.0, 'budget',   'GJEPC + In-house', 350000,  240000, 20, NULL, 'African ruby, treated.',                                               'Entry-level Sun remedy.',                                                        'Same.'),

-- ── MOON: Pearl ──────────────────────────────────────────
('PE-PREM',     'Pearl (Moti) Premium',       'मुक्ता',    'Moon',    ARRAY['Cancer'],               'White',       4.0,10.0, 6.0, 'premium',  'GIA + GRS',     2800000, 1900000, 22, NULL, 'South Sea natural pearl. Saltwater origin.',                            'Mental peace, emotional stability, maternal grace.',                              'Not for those with overactive Moon.'),
('PE-STAN',     'Pearl (Moti) Standard',      'मुक्ता',    'Moon',    ARRAY['Cancer'],               'White',       3.0, 6.0, 4.0, 'standard', 'IGI + GJEPC',    900000,  600000, 20, NULL, 'Cultured Akoya pearl, lustrous.',                                       'Calms anxiety, supports memory.',                                                'Same.'),
('PE-BUDG',     'Pearl (Moti) Budget',        'मुक्ता',    'Moon',    ARRAY['Cancer'],               'White',       2.0, 4.0, 3.0, 'budget',   'GJEPC + In-house', 250000,  170000, 20, NULL, 'Freshwater pearl.',                                                     'Entry Moon remedy.',                                                              'Same.'),

-- ── MARS: Red Coral ──────────────────────────────────────
('CO-PREM',     'Red Coral (Moonga) Premium', 'विद्रुम',   'Mars',    ARRAY['Aries','Scorpio'],      'Red',         5.0,12.0, 7.0, 'premium',  'GIA + GRS',     1800000, 1200000, 22, NULL, 'Italian Sardinian coral, oxblood color.',                              'Courage, vitality, energy.',                                                     'Avoid if Mars is yogakaraka and strong.'),
('CO-STAN',     'Red Coral Standard',         'विद्रुम',   'Mars',    ARRAY['Aries','Scorpio'],      'Red',         4.0, 8.0, 5.0, 'standard', 'IGI + GJEPC',    600000,  410000, 20, NULL, 'Japanese coral, treated.',                                              'Boosts energy.',                                                                 'Same.'),
('CO-BUDG',     'Red Coral Budget',           'विद्रुम',   'Mars',    ARRAY['Aries','Scorpio'],      'Red',         3.0, 6.0, 4.0, 'budget',   'GJEPC + In-house', 180000,  125000, 20, NULL, 'Taiwanese coral.',                                                      'Entry Mars remedy.',                                                              'Same.'),

-- ── MERCURY: Emerald ─────────────────────────────────────
('EM-PREM',     'Emerald (Panna) Premium',    'मरकत',     'Mercury', ARRAY['Gemini','Virgo'],       'Green',       2.0, 5.0, 3.0, 'premium',  'GIA + GRS',     6500000, 4500000, 22, NULL, 'Colombian Muzo origin, vivid green.',                                  'Intellect, communication, business acumen.',                                     'None notable.'),
('EM-STAN',     'Emerald Standard',           'मरकत',     'Mercury', ARRAY['Gemini','Virgo'],       'Green',       1.5, 3.5, 2.5, 'standard', 'IGI + GJEPC',   1800000, 1200000, 20, NULL, 'Zambian emerald, oiled.',                                              'Sharpens mind.',                                                                 'Same.'),
('EM-BUDG',     'Emerald Budget',             'मरकत',     'Mercury', ARRAY['Gemini','Virgo'],       'Green',       1.0, 2.5, 2.0, 'budget',   'GJEPC + In-house', 450000,  310000, 20, NULL, 'Brazilian emerald, included.',                                          'Entry Mercury remedy.',                                                          'Same.'),

-- ── JUPITER: Yellow Sapphire ─────────────────────────────
('YS-PREM',     'Yellow Sapphire (Pukhraj) Premium', 'पुष्पराग', 'Jupiter', ARRAY['Sagittarius','Pisces'],'Yellow',     3.0, 7.0, 5.0, 'premium',  'GIA + GRS',     8500000, 6000000, 22, NULL, 'Sri Lankan unheated, vivid lemon yellow.',                              'Wisdom, marriage, prosperity, luck. Most universally recommended.',             'None.'),
('YS-STAN',     'Yellow Sapphire Standard',   'पुष्पराग', 'Jupiter', ARRAY['Sagittarius','Pisces'], 'Yellow',      2.5, 5.0, 4.0, 'standard', 'IGI + GJEPC',   2500000, 1700000, 20, NULL, 'Ceylon yellow sapphire, heated.',                                       'Marriage, fortune, knowledge.',                                                  'None.'),
('YS-BUDG',     'Yellow Sapphire Budget',     'पुष्पराग', 'Jupiter', ARRAY['Sagittarius','Pisces'], 'Yellow',      2.0, 4.0, 3.0, 'budget',   'GJEPC + In-house', 600000,  410000, 20, NULL, 'Bangkok yellow sapphire.',                                              'Entry Jupiter remedy.',                                                          'None.'),

-- ── VENUS: Diamond ───────────────────────────────────────
('DI-PREM',     'Diamond (Heera) Premium',    'वज्र',      'Venus',   ARRAY['Taurus','Libra'],       'Colorless',   0.5, 2.0, 1.0, 'premium',  'GIA',           18000000,12000000, 22, NULL, 'D-color, IF clarity, excellent cut.',                                  'Luxury, marriage, artistic talent.',                                             'Avoid if Venus debilitated.'),
('DI-STAN',     'Diamond Standard',           'वज्र',      'Venus',   ARRAY['Taurus','Libra'],       'Colorless',   0.3, 1.0, 0.6, 'standard', 'IGI',            5500000, 3700000, 20, NULL, 'F-G color, VS clarity.',                                                'Marriage harmony, luxury.',                                                      'Same.'),
('DI-BUDG',     'Diamond Budget (Lab-Grown)', 'वज्र',      'Venus',   ARRAY['Taurus','Libra'],       'Colorless',   0.5, 1.5, 1.0, 'budget',   'IGI Lab-Grown', 1200000,  820000, 20, NULL, 'Lab-grown diamond, IGI certified.',                                     'Entry Venus remedy.',                                                            'Same.'),

-- ── SATURN: Blue Sapphire ────────────────────────────────
('BS-PREM',     'Blue Sapphire (Neelam) Premium', 'इंद्रनील', 'Saturn',  ARRAY['Capricorn','Aquarius'], 'Blue',        2.5, 6.0, 4.0, 'premium',  'GIA + GRS',     9500000, 6700000, 22, NULL, 'Kashmir cornflower blue, unheated.',                                   'Career, discipline, longevity. Fast-acting.',                                    'TEST 3 days first — high-impact gem.'),
('BS-STAN',     'Blue Sapphire Standard',     'इंद्रनील',  'Saturn',  ARRAY['Capricorn','Aquarius'], 'Blue',        2.0, 4.5, 3.5, 'standard', 'IGI + GJEPC',   2800000, 1900000, 20, NULL, 'Ceylon blue sapphire, royal blue.',                                     'Career growth, focus.',                                                          'Same.'),
('BS-BUDG',     'Blue Sapphire Budget',       'इंद्रनील',  'Saturn',  ARRAY['Capricorn','Aquarius'], 'Blue',        1.5, 3.0, 2.5, 'budget',   'GJEPC + In-house', 700000,  480000, 20, NULL, 'Bangkok blue sapphire.',                                                'Entry Saturn remedy.',                                                          'Same.'),

-- ── RAHU: Hessonite ──────────────────────────────────────
('HE-PREM',     'Hessonite (Gomed) Premium',  'गोमेद',     'Rahu',    ARRAY['Aquarius','Pisces'],     'Honey',       4.0, 9.0, 6.0, 'premium',  'GIA + GRS',     1200000,  820000, 22, NULL, 'Sri Lankan honey-color hessonite.',                                     'Removes Rahu obstacles, mental clarity.',                                        'None.'),
('HE-STAN',     'Hessonite Standard',         'गोमेद',     'Rahu',    ARRAY['Aquarius','Pisces'],     'Honey',       3.0, 6.0, 5.0, 'standard', 'IGI + GJEPC',    400000,  270000, 20, NULL, 'Ceylon hessonite.',                                                     'Rahu remedy.',                                                                   'None.'),
('HE-BUDG',     'Hessonite Budget',           'गोमेद',     'Rahu',    ARRAY['Aquarius','Pisces'],     'Honey',       2.5, 5.0, 4.0, 'budget',   'GJEPC + In-house', 120000,   80000, 20, NULL, 'African hessonite.',                                                    'Entry Rahu remedy.',                                                             'None.'),

-- ── KETU: Cat''s Eye ─────────────────────────────────────
('CE-PREM',     'Cat''s Eye (Vaidurya) Premium', 'वैदूर्य', 'Ketu',    ARRAY['Scorpio'],               'Honey-Yellow',2.5, 6.0, 4.0, 'premium',  'GIA + GRS',     1500000, 1050000, 22, NULL, 'Ceylon chrysoberyl cat''s-eye, sharp chatoyancy.',                      'Spiritual insight, protection from sudden setbacks.',                            'None.'),
('CE-STAN',     'Cat''s Eye Standard',        'वैदूर्य',  'Ketu',    ARRAY['Scorpio'],               'Honey-Yellow',2.0, 4.0, 3.0, 'standard', 'IGI + GJEPC',    500000,  340000, 20, NULL, 'Ceylon chrysoberyl, clear band.',                                       'Ketu remedy.',                                                                   'None.'),
('CE-BUDG',     'Cat''s Eye Budget',          'वैदूर्य',  'Ketu',    ARRAY['Scorpio'],               'Honey-Yellow',1.5, 3.0, 2.5, 'budget',   'GJEPC + In-house', 150000,  100000, 20, NULL, 'Quartz cat''s-eye.',                                                    'Entry Ketu remedy.',                                                             'None.')
ON CONFLICT (sku) DO NOTHING;
